# Change these first
owner: NIKEYIer # Your GitHub organization or username, where this repository lives
repo: status.beiqilai.com # The name of this repository

sites:
  - name: Beiqilai 備起來 - Get Ready to Teach
    url: https://www.beiqilai.com/favicon.ico
    icon: https://www.beiqilai.com/favicon.ico

status-website:
  theme: light

  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.beiqilai.com
  # baseUrl: /your-repo-name
  favicon: https://www.beiqilai.com/favicon.ico
  logoUrl: https://www.beiqilai.com/_nuxt/beiqilai_typography.09fbd160.svg
  name: Beiqilai 備起來
  introTitle: "**Beiqilai** System Status"
  introMessage: "[Beiqilai](https://www.beiqilai.com) - Get Ready to Teach"

  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://www.beiqilai.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
